---
apiVersion: v1
kind: Namespace
metadata:
  name: marketplace-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: manager
  namespace: marketplace-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: marketplace-system
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      serviceAccountName: manager
      containers:
      - command:
        - /manager
        args:
        - --enable-leader-election
        image: criticalstack/marketplace:latest
        name: manager
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
      terminationGracePeriodSeconds: 10
